# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CORTES.py
# Created on: 2016-11-07 21:13:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
TB_VIVIENDAS_CORTES = "TB_VIVIENDAS_CORTES"
TB_RUTAS_PUNTOS_MIN = "TB_RUTAS_PUNTOS_MIN"
TB_RUTAS_LINEAS_Merge = "C:\\Users\\fsoto\\Documents\\ArcGIS\\Default.gdb\\TB_RUTAS_LINEAS_Merge"
TB_RUTAS_PUNTOS_MIN_Merge = "C:\\Users\\fsoto\\Documents\\ArcGIS\\Default.gdb\\TB_RUTAS_PUNTOS_MIN_Merge"
TB_RUTAS_PUNTOS_MIN_Merge_So = "C:\\Users\\fsoto\\Documents\\ArcGIS\\Default.gdb\\TB_RUTAS_PUNTOS_MIN_Merge_So"
TB_RUTAS_PUNTOS_MIN__2_ = "TB_RUTAS_PUNTOS_MIN"

# Process: Merge
arcpy.Merge_management("", TB_RUTAS_LINEAS_Merge, "UBIGEO \"UBIGEO\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,UBIGEO,-1,-1,TB_RUTAS_PUNTOS_MIN,UBIGEO,-1,-1;CODCCPP \"CODCCPP\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,CODCCPP,-1,-1,TB_RUTAS_PUNTOS_MIN,CODCCPP,-1,-1;ZONA \"ZONA\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,ZONA,-1,-1,TB_RUTAS_PUNTOS_MIN,ZONA,-1,-1;MANZANA \"MANZANA\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,MANZANA,-1,-1,TB_RUTAS_PUNTOS_MIN,MANZANA,-1,-1;AEU \"AEU\" true true false 5 Short 0 5 ,First,#,TB_VIVIENDAS_CORTES,AEU,-1,-1,TB_RUTAS_PUNTOS_MIN,AEU,-1,-1;ID_REG_OR \"ID_REG_OR\" true true false 5 Short 0 5 ,First,#,TB_VIVIENDAS_CORTES,ID_REG_OR,-1,-1,TB_RUTAS_PUNTOS_MIN,ID_REG_OR,-1,-1")

# Process: Add Field
arcpy.AddField_management(TB_RUTAS_PUNTOS_MIN, "FLG", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(TB_RUTAS_PUNTOS_MIN__2_, "FLG", "1", "VB", "")

# Process: Merge (2)
arcpy.Merge_management("TB_VIVIENDAS_CORTES;TB_RUTAS_PUNTOS_MIN", TB_RUTAS_PUNTOS_MIN_Merge, "UBIGEO \"UBIGEO\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,UBIGEO,-1,-1,TB_RUTAS_PUNTOS_MIN,UBIGEO,-1,-1;CODCCPP \"CODCCPP\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,CODCCPP,-1,-1,TB_RUTAS_PUNTOS_MIN,CODCCPP,-1,-1;ZONA \"ZONA\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,ZONA,-1,-1,TB_RUTAS_PUNTOS_MIN,ZONA,-1,-1;MANZANA \"MANZANA\" true true false 254 Text 0 0 ,First,#,TB_VIVIENDAS_CORTES,MANZANA,-1,-1,TB_RUTAS_PUNTOS_MIN,MANZANA,-1,-1;AEU \"AEU\" true true false 5 Short 0 5 ,First,#,TB_VIVIENDAS_CORTES,AEU,-1,-1,TB_RUTAS_PUNTOS_MIN,AEU,-1,-1;ID_REG_OR \"ID_REG_OR\" true true false 5 Short 0 5 ,First,#,TB_VIVIENDAS_CORTES,ID_REG_OR,-1,-1,TB_RUTAS_PUNTOS_MIN,ID_REG_OR,-1,-1;FLG \"FLG\" true true false 0 Short 0 0 ,First,#,TB_RUTAS_PUNTOS_MIN,FLG,-1,-1")

# Process: Sort
arcpy.Sort_management(TB_RUTAS_PUNTOS_MIN_Merge, TB_RUTAS_PUNTOS_MIN_Merge_So, "UBIGEO ASCENDING;CODCCPP ASCENDING;ZONA ASCENDING;MANZANA ASCENDING;AEU ASCENDING;ID_REG_OR DESCENDING;FLG DESCENDING", "UR")

# Process: Delete Identical
arcpy.DeleteIdentical_management(TB_RUTAS_PUNTOS_MIN_Merge_So, "UBIGEO;CODCCPP;ZONA;MANZANA;AEU", "", "0")

