# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CREAR_LINEAS_AEU_SEGUNDA_PASADA.py
# Created on: 2016-09-23 15:05:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TB_PRIMERA_VIVIENDA_AEU_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_PRIMERA_VIVIENDA_AEU.shp"
TB_RUTAS_1_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_1.shp"
TB_RUTAS_PREPARACION_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_PREPARACION.shp"
TB_INTERSECT_RUTAS_PRIMERA_VIVIENDA = "in_memory\\TB_INTERSECT_RUTAS_PRIMERA_VIVIENDA"
TB_RUTAS_1_Layer = "TB_RUTAS_1_Layer"
TB_RUTAS_1_Layer__4_ = "TB_RUTAS_1_Layer"
TB_RUTAS_1_1_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_1_1.shp"
TB_RUTAS_1_Layer__5_ = "TB_RUTAS_1_Layer"
TB_RUTAS_1_2_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_1_2.shp"
TB_RUTAS_2_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_2.shp"
TB_RUTASS_shp = "in_memory\\TB_RUTASS"
TB_RUTASS_Sort = "in_memory\\TB_RUTASS_Sort"
TB_RUTASS_Sort_Layer = "TB_RUTASS_Sort_Layer"
MZS_AEU_dbf= "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\EnumerarAEUViviendas\\MZS_AEU.dbf"
TB_RUTAS_LINEAS_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_LINEAS.shp"

if arcpy.Exists(TB_RUTAS_1_1_shp):
    arcpy.Delete_management(TB_RUTAS_1_1_shp)

if arcpy.Exists(TB_RUTAS_1_2_shp):
    arcpy.Delete_management(TB_RUTAS_1_2_shp)

if arcpy.Exists(TB_RUTAS_2_shp):
    arcpy.Delete_management(TB_RUTAS_2_shp)

if arcpy.Exists(TB_RUTAS_LINEAS_shp):
    arcpy.Delete_management(TB_RUTAS_LINEAS_shp)

# Process: Select (2)
arcpy.Select_analysis(TB_RUTAS_1_shp, TB_RUTAS_1_1_shp, "\"AEU\"<>0")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(TB_RUTAS_1_shp, TB_RUTAS_1_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;ZONA ZONA VISIBLE NONE;MANZANA MANZANA VISIBLE NONE;AEU AEU VISIBLE NONE;FLG_MZ FLG_MZ VISIBLE NONE")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(TB_RUTAS_1_Layer, "NEW_SELECTION", "\"AEU\"=0")

# Process: Intersect (5)
arcpy.Intersect_analysis("D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_PRIMERA_VIVIENDA_AEU.shp #;TB_RUTAS_1_Layer #", TB_INTERSECT_RUTAS_PRIMERA_VIVIENDA, "ALL", "0.32 Meters", "INPUT")

# Process: Add Join
arcpy.AddJoin_management(TB_RUTAS_1_Layer__4_, "FID", TB_INTERSECT_RUTAS_PRIMERA_VIVIENDA, "FID_TB_RUTAS_1", "KEEP_ALL")

# Process: Select
arcpy.Select_analysis(TB_RUTAS_1_Layer__5_, TB_RUTAS_1_2_shp, "")

# Process: Add Field
arcpy.AddField_management(TB_RUTAS_1_2_shp, "UBIGEO", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(TB_RUTAS_1_2_shp, "UBIGEO", "[TB_RUTAS_1]", "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(TB_RUTAS_1_2_shp, "ZONA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(TB_RUTAS_1_2_shp, "ZONA", "[TB_RUTAS_2]", "VB", "")

# Process: Add Field (3)
arcpy.AddField_management(TB_RUTAS_1_2_shp, "MANZANA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(TB_RUTAS_1_2_shp, "MANZANA", "[TB_RUTAS_3]", "VB", "")

# Process: Add Field (4)
arcpy.AddField_management(TB_RUTAS_1_2_shp, "AEU", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(TB_RUTAS_1_2_shp, "AEU", "[TB_INTER_5]", "VB", "")

# Process: Add Field (5)
arcpy.AddField_management(TB_RUTAS_1_2_shp, "FLG_MZ", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(TB_RUTAS_1_2_shp, "FLG_MZ", "[TB_INTE_11]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(TB_RUTAS_1_2_shp, "TB_RUTAS_1;TB_RUTAS_2;TB_RUTAS_3;TB_RUTAS_4;TB_RUTAS_5;TB_INTERSE;TB_INTER_1;TB_INTER_2;TB_INTER_3;TB_INTER_4;TB_INTER_5;TB_INTER_6;TB_INTER_7;TB_INTER_8;TB_INTER_9;TB_INTE_10;TB_INTE_11")

# Process: Select (3)
arcpy.Select_analysis(TB_RUTAS_PREPARACION_shp, TB_RUTAS_2_shp, "\"FLG_MZ\"=0")

# Process: Delete Field (2)
arcpy.DeleteField_management(TB_RUTAS_2_shp, "ORIG_FID")

# Process: Merge (2)
arcpy.Merge_management([TB_RUTAS_1_1_shp,TB_RUTAS_1_2_shp,TB_RUTAS_2_shp],TB_RUTASS_shp)
# Process: Sort
arcpy.Sort_management(TB_RUTASS_shp, TB_RUTASS_Sort, "UBIGEO ASCENDING;ZONA ASCENDING;MANZANA ASCENDING;AEU ASCENDING", "UR")


arcpy.MakeFeatureLayer_management(TB_RUTASS_Sort, TB_RUTASS_Sort_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;ZONA ZONA VISIBLE NONE;MANZANA MANZANA VISIBLE NONE;AEU AEU VISIBLE NONE;FLG_MZ FLG_MZ VISIBLE NONE")

# Process: Add Field
arcpy.AddField_management(TB_RUTASS_Sort_Layer, "IDRUTA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(TB_RUTASS_Sort_Layer, "IDRUTA", "[UBIGEO] & [ZONA] & [MANZANA] & [AEU]", "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(MZS_AEU_dbf, "IDRUTA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(MZS_AEU_dbf, "IDRUTA", "[UBIGEO] & [ZONA] & [MANZANA] & [AEU]", "VB", "")

# Process: Add Join
arcpy.AddJoin_management(TB_RUTASS_Sort_Layer, "IDRUTA", MZS_AEU_dbf, "IDRUTA", "KEEP_ALL")

# Process: Copy Features
arcpy.CopyFeatures_management(TB_RUTASS_Sort_Layer, TB_RUTAS_LINEAS_shp, "", "0", "0", "0")

# Process: Add Field (3)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "UBIGEO", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "ZONA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "MANZANA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Add Field (6)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "AEU", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (7)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "FLG_MZ", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "UBIGEO", "[TB_RUTASS_]", "VB", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "ZONA", "[TB_RUTASS1]", "VB", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "MANZANA", "[TB_RUTAS_1]", "VB", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "AEU", "[TB_RUTAS_2]", "VB", "")

# Process: Calculate Field (7)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "FLG_MZ", "[TB_RUTAS_3]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(TB_RUTAS_LINEAS_shp, "TB_RUTASS_;TB_RUTASS1;TB_RUTAS_1;TB_RUTAS_2;TB_RUTAS_3;TB_RUTAS_4;MZS_AEU_OI;MZS_AEU_UB;MZS_AEU_ZO;MZS_AEU_MA;MZS_AEU_AE;MZS_AEU_CA;MZS_AEU_ID")

