# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CREAR_LINEAS_AEU.py
# Created on: 2016-09-21 15:46:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TB_SEGUNDA_VIVIENDA_AEU_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_SEGUNDA_VIVIENDA_AEU.shp"
TB_RUTAS_PREPARACION_shp__3_ = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_PREPARACION.shp"
TB_RUTAS_Layer__2_ = "TB_RUTAS_Layer"
TB_RUTAS_1_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_1.shp"
TB_INTERSECT_RUTAS_VIVIENDA_SEGUNDO_PUNTO = "in_memory\\TB_INTERSECT_RUTAS_VIVIENDA_SEGUNDO_PUNTO"
TB_INT_RUTAS_VIVIENDAS_AEU_MAX = "in_memory\\TB_INT_RUTAS_VIVIENDAS_AEU_MAX"
TB_RUTAS_Layer = "TB_RUTAS_Layer"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(TB_RUTAS_PREPARACION_shp__3_, TB_RUTAS_Layer, "\"FLG_MZ\"=1", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;ZONA ZONA VISIBLE NONE;MANZANA MANZANA VISIBLE NONE;FLG_MZ FLG_MZ VISIBLE NONE;ORIG_FID ORIG_FID VISIBLE NONE")

# Process: Intersect (3)
arcpy.Intersect_analysis("TB_RUTAS_Layer #;D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_SEGUNDA_VIVIENDA_AEU.shp #", TB_INTERSECT_RUTAS_VIVIENDA_SEGUNDO_PUNTO, "ALL", "0.35 Meters", "INPUT")

# Process: Summary Statistics (3)
arcpy.Statistics_analysis(TB_INTERSECT_RUTAS_VIVIENDA_SEGUNDO_PUNTO, TB_INT_RUTAS_VIVIENDAS_AEU_MAX, "AEU MAX", "FID_TB_RUTAS_PREPARACION")

# Process: Add Join
arcpy.AddJoin_management(TB_RUTAS_Layer, "FID", TB_INT_RUTAS_VIVIENDAS_AEU_MAX, "FID_TB_RUTAS_PREPARACION", "KEEP_ALL")

# Process: Copy Features (2)
arcpy.CopyFeatures_management(TB_RUTAS_Layer__2_, TB_RUTAS_1_shp, "", "0", "0", "0")

