# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# iterator.py
# Created on: 2016-08-04 10:44:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Shape020601003000001_shp = "D:\\ShapesPruebasSegmentacionUrbana\\ShapesFinal2\\Shape020601003000001.shp"

# Process: Iterate Row Selection
arcpy.IterateRowSelection_mb(Shape020601003000001_shp, "", "false")

