# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# OBTENER_LAYER_MAPAS_ORDENADO.py
# Created on: 2016-08-31 19:28:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
TB_MZS_TRABAJO_shp__2_ = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\TB_MZS_TRABAJO.shp"
MZS_AEU_dbf__2_ = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\MZS_AEU.dbf"
TB_MZS_TRABAJO_Layer = "TB_MZS_TRABAJO_Layer"
TB_MZS_TRABAJO_Layer__3_ = "TB_MZS_TRABAJO_Layer"
TB_MZS_FINAL_shp = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\TB_MZS_FINAL.shp"
ZONA_AEU = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\ZONA_AEU"
AEU_CANT_VIV = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\AEU_CANT_VIV"
MZS_AEU_2 = "D:\\ShapesPruebasSegmentacionUrbana\\Renumerar\\MZS_AEU_2"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(TB_MZS_TRABAJO_shp__2_, TB_MZS_TRABAJO_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;ID ID VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;CCDD CCDD VISIBLE NONE;CCPP CCPP VISIBLE NONE;CCDI CCDI VISIBLE NONE;ZONA ZONA VISIBLE NONE;MANZANA MANZANA VISIBLE NONE;CODCCPP CODCCPP VISIBLE NONE;NOMCCPP NOMCCPP VISIBLE NONE;DEPARTAMEN DEPARTAMEN VISIBLE NONE;PROVINCIA PROVINCIA VISIBLE NONE;DISTRITO DISTRITO VISIBLE NONE;VIV_MZ VIV_MZ VISIBLE NONE;xCentroid xCentroid VISIBLE NONE;yCentroid yCentroid VISIBLE NONE;cant_aeus cant_aeus VISIBLE NONE;AEU AEU HIDDEN NONE;AREA AREA VISIBLE NONE;IDMANZANA IDMANZANA VISIBLE NONE")

# Process: Add Join
arcpy.AddJoin_management(TB_MZS_TRABAJO_Layer, "IDMANZANA", MZS_AEU_dbf__2_, "IDMANZANA", "KEEP_ALL")

# Process: Dissolve
arcpy.Dissolve_management(TB_MZS_TRABAJO_Layer__3_, TB_MZS_FINAL_shp, "TB_MZS_TRABAJO.UBIGEO;TB_MZS_TRABAJO.ZONA;MZS_AEU.AEU", "TB_MZS_TRABAJO.IDMANZANA FIRST", "MULTI_PART", "DISSOLVE_LINES")

# Process: Summary Statistics
arcpy.Statistics_analysis(MZS_AEU_dbf__2_, ZONA_AEU, "IDMANZANA COUNT", "UBIGEO;ZONA;AEU")

# Process: Summary Statistics (2)
arcpy.Statistics_analysis(MZS_AEU_dbf__2_, AEU_CANT_VIV, "VIV_AEU SUM", "UBIGEO;ZONA;AEU")

# Process: Summary Statistics (3)
arcpy.Statistics_analysis(MZS_AEU_dbf__2_, MZS_AEU_2, "VIV_AEU SUM", "UBIGEO;ZONA;AEU;IDMANZANA")

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb("", "", "false")

