# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SEGUNDA_PASADA.py
# Created on: 2016-09-24 13:32:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:


TB_RUTAS_LINEAS_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_LINEAS.shp"
TB_RUTAS_DISSOLVE = "in_memory\\TB_RUTAS_DISSOLVE"
TB_RUTAS_DISSOLVE__2_ = "in_memory\\TB_RUTAS_DISSOLVE"
TB_RUTAS_DISSOLVE_Select2 = "in_memory\\TB_RUTAS_DISSOLVE_Select2"
TB_RUTAS_DISSOLVE_Select3 = "in_memory\\TB_RUTAS_DISSOLVE_Select3"
TB_RUTAS_DISSOLVE_Select3_Bu = "in_memory\\TB_RUTAS_DISSOLVE_Select3_Bu"
TB_RUTAS_INTERSECT = "in_memory\\TB_RUTAS_INTERSECT"
TB_RUTAS_SELECT_ZONA__2_ = "in_memory\\TB_RUTAS_SELECT_ZONA"
TB_RUTAS_SELECT_ZONA_shp__2_ = "in_memory\\TB_RUTAS_SELECT_ZONA"
TB_RUTAS_INTERSECT_SORT_Laye = "TB_RUTAS_INTERSECT_SORT_Laye"
TB_RUTAS_INTERSECT_SORT_Stat1 = "in_memory\\TB_RUTAS_INTERSECT_SORT_Stat1"
TB_RUTAS_SELECT_ZONA__4_ = "in_memory\\TB_RUTAS_SELECT_ZONA"
TB_RUTAS_INTERSECT_SORT = "in_memory\\TB_RUTAS_INTERSECT_SORT"
TB_RUTAS_INTERSECT_Sort_Stat__2_ = "in_memory\\TB_RUTAS_INTERSECT_SORT_Stat1"
TB_RUTAS_DISSOLVE_shp__3_ = "in_memory\\TB_RUTAS_DISSOLVE"
TB_RUTAS_INTERSECT_SORT_Laye__2_ = "TB_RUTAS_INTERSECT_SORT_Laye"
TB_SEGUNDA_PASADA_shp = "D:\\ShapesPruebasSegmentacionUrbana\\SegundaPasada\\TB_SEGUNDA_PASADA.shp"
TB_RUTAS_SELECT_ZONA = "in_memory\\TB_RUTAS_SELECT_ZONA"
TB_RUTAS_DISSOLVE_Select2_Fe = "in_memory\\TB_RUTAS_DISSOLVE_Select2_Fe"
TB_RUTAS_INTERSECT_Sort_Stat__4_ = "in_memory\\TB_RUTAS_INTERSECT_SORT_Stat1"

# Process: Dissolve
arcpy.Dissolve_management(TB_RUTAS_LINEAS_shp, TB_RUTAS_DISSOLVE, "UBIGEO;ZONA;AEU;FLG_MZ", "MANZANA COUNT;CANT_VIV SUM", "MULTI_PART", "DISSOLVE_LINES")

# Process: Add Field (7)
arcpy.AddField_management(TB_RUTAS_DISSOLVE, "ID_RUTAAEU", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (7)
arcpy.CalculateField_management(TB_RUTAS_DISSOLVE_shp__3_, "ID_RUTAAEU", "[UBIGEO] & [ZONA] & [AEU]", "VB", "")

# Process: Select (2)
arcpy.Select_analysis(TB_RUTAS_DISSOLVE__2_, TB_RUTAS_DISSOLVE_Select3, "\"SUM_CANT_VIV\"<=8 AND \"FLG_MZ\"=0")

# Process: Buffer
arcpy.Buffer_analysis(TB_RUTAS_DISSOLVE_Select3, TB_RUTAS_DISSOLVE_Select3_Bu, "25 Meters", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Select
arcpy.Select_analysis(TB_RUTAS_DISSOLVE__2_, TB_RUTAS_DISSOLVE_Select2, "\"FLG_MZ\"=1")

# Process: Feature Vertices To Points
arcpy.FeatureVerticesToPoints_management(TB_RUTAS_DISSOLVE_Select2, TB_RUTAS_DISSOLVE_Select2_Fe, "START")

# Process: Intersect
arcpy.Intersect_analysis("in_memory\\TB_RUTAS_DISSOLVE_Select3_Bu #;in_memory\\TB_RUTAS_DISSOLVE_Select2_Fe #", TB_RUTAS_INTERSECT, "ALL", "", "INPUT")

# Process: Select (4)
arcpy.Select_analysis(TB_RUTAS_INTERSECT, TB_RUTAS_SELECT_ZONA, "\"UBIGEO\"= \"UBIGEO_1\" AND \"ZONA\"=\"ZONA_1\"")

# Process: Delete Identical
arcpy.DeleteIdentical_management(TB_RUTAS_SELECT_ZONA, "UBIGEO;ZONA;AEU_1;FLG_MZ_1", "", "0")

# Process: Add Field (5)
arcpy.AddField_management(TB_RUTAS_SELECT_ZONA__2_, "TOTAL_VIV", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(TB_RUTAS_SELECT_ZONA_shp__2_, "TOTAL_VIV", "[SUM_CANT_VIV]+ [SUM_CANT_VIV_1]", "VB", "")

# Process: Sort
arcpy.Sort_management(TB_RUTAS_SELECT_ZONA__4_, TB_RUTAS_INTERSECT_SORT, "UBIGEO ASCENDING;ZONA ASCENDING;AEU ASCENDING;TOTAL_VIV ASCENDING", "UR")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(TB_RUTAS_INTERSECT_SORT, TB_RUTAS_INTERSECT_SORT_Laye, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;FID_TB_RUTAS_DISSOLVE_Select3_Bu FID_TB_RUTAS_DISSOLVE_Select3_Bu VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;ZONA ZONA VISIBLE NONE;AEU AEU VISIBLE NONE;FLG_MZ FLG_MZ VISIBLE NONE;COUNT_MANZANA COUNT_MANZANA VISIBLE NONE;SUM_CANT_VIV SUM_CANT_VIV VISIBLE NONE;ID_RUTAAEU ID_RUTAAEU VISIBLE NONE;BUFF_DIST BUFF_DIST VISIBLE NONE;ORIG_FID ORIG_FID VISIBLE NONE;FID_TB_RUTAS_DISSOLVE_Select2_Fe FID_TB_RUTAS_DISSOLVE_Select2_Fe VISIBLE NONE;UBIGEO_1 UBIGEO_1 VISIBLE NONE;ZONA_1 ZONA_1 VISIBLE NONE;AEU_1 AEU_1 VISIBLE NONE;FLG_MZ_1 FLG_MZ_1 VISIBLE NONE;COUNT_MANZANA_1 COUNT_MANZANA_1 VISIBLE NONE;SUM_CANT_VIV_1 SUM_CANT_VIV_1 VISIBLE NONE;ID_RUTAAEU_1 ID_RUTAAEU_1 VISIBLE NONE;ORIG_FID_1 ORIG_FID_1 VISIBLE NONE;TOTAL_VIV TOTAL_VIV VISIBLE NONE")

# Process: Summary Statistics (3)
arcpy.Statistics_analysis(TB_RUTAS_INTERSECT_SORT_Laye, TB_RUTAS_INTERSECT_SORT_Stat1, "FID MIN", "UBIGEO;ZONA;AEU")

# Process: Add Field (6)
arcpy.AddField_management(TB_RUTAS_INTERSECT_SORT_Stat1, "flg_esc", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(TB_RUTAS_INTERSECT_Sort_Stat__2_, "flg_esc", "1", "VB", "")

# Process: Add Join
arcpy.AddJoin_management(TB_RUTAS_INTERSECT_SORT_Laye, "FID", TB_RUTAS_INTERSECT_Sort_Stat__4_, "MIN_FID", "KEEP_COMMON")

# Process: Select (3)
arcpy.Select_analysis(TB_RUTAS_INTERSECT_SORT_Laye__2_, TB_SEGUNDA_PASADA_shp, "\"flg_esc\"=1 and \"TOTAL_VIV\"<=16")

# Process: Add Field
arcpy.AddField_management(TB_SEGUNDA_PASADA_shp, "UBIGEO", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(TB_SEGUNDA_PASADA_shp, "ZONA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(TB_SEGUNDA_PASADA_shp, "AEU", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(TB_SEGUNDA_PASADA_shp, "AEU_1", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(TB_SEGUNDA_PASADA_shp, "UBIGEO", "[TB_RUTAS_1]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(TB_SEGUNDA_PASADA_shp, "ZONA", "[TB_RUTAS_2]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(TB_SEGUNDA_PASADA_shp, "AEU", "[TB_RUTAS_3]", "VB", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(TB_SEGUNDA_PASADA_shp, "AEU_1", "[TB_RUTA_13]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(TB_SEGUNDA_PASADA_shp, "TB_RUTAS_I;TB_RUTAS_1;TB_RUTAS_2;TB_RUTAS_3;TB_RUTAS_4;TB_RUTAS_5;TB_RUTAS_6;TB_RUTAS_7;TB_RUTAS_8;TB_RUTAS_9;TB_RUTA_10;TB_RUTA_11;TB_RUTA_12;TB_RUTA_13;TB_RUTA_14;TB_RUTA_15;TB_RUTA_16;TB_RUTA_17;TB_RUTA_18;TB_RUTA_19;TB_RUTA_20;TB_RUTA_21;TB_RUTA_22;TB_RUTA_23;TB_RUTA_24;TB_RUTA_25;TB_RUTA_26")

