# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# UNION.py
# Created on: 2016-09-23 15:53:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TB_RUTASS_Sort_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTASS_Sort.shp"
MZS_AEU_dbf = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\EnumerarAEUViviendas\\MZS_AEU.dbf"
TB_RUTASS_Sort_Layer = "TB_RUTASS_Sort_Layer"
TB_RUTASS_Sort_Layer__4_ = "TB_RUTASS_Sort_Layer"
MZS_AEU_dbf__4_ = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\EnumerarAEUViviendas\\MZS_AEU.dbf"
TB_RUTASS_Sort_Layer__3_ = "TB_RUTASS_Sort_Layer"
MZS_AEU_dbf__3_ = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\EnumerarAEUViviendas\\MZS_AEU.dbf"
TB_RUTASS_Sort_Layer__5_ = "TB_RUTASS_Sort_Layer"
TB_RUTAS_LINEAS_shp = "D:\\ShapesPruebasSegmentacionUrbana\\AEU\\CrearRepresentacionAEU\\TB_RUTAS_LINEAS.shp"


# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(TB_RUTASS_Sort_shp, TB_RUTASS_Sort_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;UBIGEO UBIGEO VISIBLE NONE;ZONA ZONA VISIBLE NONE;MANZANA MANZANA VISIBLE NONE;AEU AEU VISIBLE NONE;FLG_MZ FLG_MZ VISIBLE NONE")

# Process: Add Field
arcpy.AddField_management(TB_RUTASS_Sort_Layer, "IDRUTA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(TB_RUTASS_Sort_Layer__3_, "IDRUTA", "[UBIGEO] & [ZONA] & [MANZANA] & [AEU]", "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(MZS_AEU_dbf, "IDRUTA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(MZS_AEU_dbf__3_, "IDRUTA", "[UBIGEO] & [ZONA] & [MANZANA] & [AEU]", "VB", "")

# Process: Add Join
arcpy.AddJoin_management(TB_RUTASS_Sort_Layer__4_, "IDRUTA", MZS_AEU_dbf__4_, "IDRUTA", "KEEP_ALL")

# Process: Copy Features
arcpy.CopyFeatures_management(TB_RUTASS_Sort_Layer__5_, TB_RUTAS_LINEAS_shp, "", "0", "0", "0")

# Process: Add Field (3)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "UBIGEO", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "ZONA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "MANZANA", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Add Field (6)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "AEU", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (7)
arcpy.AddField_management(TB_RUTAS_LINEAS_shp, "FLG_MZ", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "UBIGEO", "[TB_RUTASS_]", "VB", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "ZONA", "[TB_RUTASS1]", "VB", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "MANZANA", "[TB_RUTAS_1]", "VB", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "AEU", "[TB_RUTAS_2]", "VB", "")

# Process: Calculate Field (7)
arcpy.CalculateField_management(TB_RUTAS_LINEAS_shp, "FLG_MZ", "[TB_RUTAS_3]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(TB_RUTAS_LINEAS_shp, "TB_RUTASS_;TB_RUTASS1;TB_RUTAS_1;TB_RUTAS_2;TB_RUTAS_3;TB_RUTAS_4;MZS_AEU_OI;MZS_AEU_UB;MZS_AEU_ZO;MZS_AEU_MA;MZS_AEU_AE;MZS_AEU_CA;MZS_AEU_ID")

